my_places = ['japan', 'texas', 'england', 'ireland', 'sweden']
print(my_places)
print(sorted(my_places))
print(my_places)
print(sorted(my_places, reverse=True))
print(my_places)
my_places.reverse()
print(my_places)
my_places.reverse()
print(my_places)
my_places.sort()
print(my_places)
my_places.sort(reverse=True)
print(my_places)
